In [1]:
db = [ 1,"halchii", "ok" ]

In [2]:
db


[1, 'halchii', 'ok']

In [3]:
type(db)

list

In [4]:
db.append(5342)
db

[1, 'halchii', 'ok', 5342]

In [5]:
db[1:3]

['halchii', 'ok']

In [6]:
db = [ [1,"mukesh",2321,"ok"],[2,"halchii",2322,"lol"],[3,"soumya",1111,"bud"],[4,"ankit",9877,"pubg"] ]
db
type(db)

list

In [7]:
db

[[1, 'mukesh', 2321, 'ok'],
 [2, 'halchii', 2322, 'lol'],
 [3, 'soumya', 1111, 'bud'],
 [4, 'ankit', 9877, 'pubg']]

In [8]:
db[:]

[[1, 'mukesh', 2321, 'ok'],
 [2, 'halchii', 2322, 'lol'],
 [3, 'soumya', 1111, 'bud'],
 [4, 'ankit', 9877, 'pubg']]

TypeError: list indices must be integers or slices, not tuple

In [14]:
column(db,1)

NameError: name 'column' is not defined

In [15]:
zip(*db)[1]

TypeError: 'zip' object is not subscriptable

In [19]:
list(zip(*db))[1]

('mukesh', 'halchii', 'soumya', 'ankit')

In [20]:
db

[[1, 'mukesh', 2321, 'ok'],
 [2, 'halchii', 2322, 'lol'],
 [3, 'soumya', 1111, 'bud'],
 [4, 'ankit', 9877, 'pubg']]

In [21]:
db

[[1, 'mukesh', 2321, 'ok'],
 [2, 'halchii', 2322, 'lol'],
 [3, 'soumya', 1111, 'bud'],
 [4, 'ankit', 9877, 'pubg']]

In [17]:
db[:,1
  ]

TypeError: list indices must be integers or slices, not tuple

In [23]:
import numpy


In [24]:
numpy.array(db)

array([['1', 'mukesh', '2321', 'ok'],
       ['2', 'halchii', '2322', 'lol'],
       ['3', 'soumya', '1111', 'bud'],
       ['4', 'ankit', '9877', 'pubg']], dtype='<U11')

In [25]:
DB = numpy.array(db)

In [26]:
D

NameError: name 'D' is not defined

In [28]:
DB[:,1]

array(['mukesh', 'halchii', 'soumya', 'ankit'], dtype='<U11')

In [29]:
DB

array([['1', 'mukesh', '2321', 'ok'],
       ['2', 'halchii', '2322', 'lol'],
       ['3', 'soumya', '1111', 'bud'],
       ['4', 'ankit', '9877', 'pubg']], dtype='<U11')

In [30]:
DB[:]

array([['1', 'mukesh', '2321', 'ok'],
       ['2', 'halchii', '2322', 'lol'],
       ['3', 'soumya', '1111', 'bud'],
       ['4', 'ankit', '9877', 'pubg']], dtype='<U11')

In [31]:
DB[1:3,1:3]

array([['halchii', '2322'],
       ['soumya', '1111']], dtype='<U11')

In [32]:
DB.shape

(4, 4)

In [37]:
DB1= numpy.array([1,2,3,4,5,6,7,8])

In [35]:
DB1

array([1, 2, 3, 4, 5, 6, 8])

In [43]:
DB1.reshape(4,2).shape


(4, 2)

In [40]:
DB1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
DB1.reshape(-1,1).shape

(8, 1)

In [42]:
DB1.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])