In [59]:
import pandas
import numpy

In [60]:
dataset = pandas.read_csv(r"C:\Users\mukes\OneDrive\Documents\Projects\SummerDir\datasets\50_Startups.csv")

In [61]:
dataset.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [10]:
state = dataset['State']

In [12]:
state.head(5)

0      New York
1    California
2       Florida
3      New York
4       Florida
Name: State, dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
state_le = LabelEncoder()

In [21]:
state_final = state_le.fit_transform(state).reshape(-1,1)

In [23]:
state_final.shape

(50, 1)

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
state_ohe = OneHotEncoder()

In [28]:
state_dump = state_ohe.fit_transform(state_final)

In [31]:
state_fields = state_dump.toarray()[:,0:2]

In [32]:
state_fields

array([[0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [35]:
y = dataset['Profit']

In [37]:
X = dataset[[ 'R&D Spend','Administration','Marketing Spend' ]]

In [43]:
X_final = numpy.hstack( (X, state_fields) )

In [46]:
X_final

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 0.0000000e+00,
        1.00

In [47]:
# we took every data now we need to split the data for training and testing.
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.20, random_state=42)

In [50]:
X_train.shape

(40, 5)

In [51]:
X_test.shape

(10, 5)

In [52]:
# Now Data is pre-processed all we need to do is implement Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression

In [54]:
model = LinearRegression()

In [55]:
# algo
model.fit(X_train,y_train)

LinearRegression()

In [56]:
model.coef_

array([ 8.05630064e-01, -6.87878823e-02,  2.98554429e-02, -6.98775997e+00,
        9.31805246e+02])

In [57]:
y_test
# Here is the actual data.

13    134307.35
39     81005.76
30     99937.59
45     64926.08
17    125370.37
48     35673.41
26    105733.54
25    107404.34
32     97427.84
19    122776.86
Name: Profit, dtype: float64

In [58]:
y_hat = model.predict(X_test)
y_hat
# Here is the predicted data 

array([126362.87908254,  84608.45383635,  99677.49425148,  46357.46068582,
       128750.48288503,  50912.41741885, 109741.35032702, 100643.24281646,
        97599.27574595, 113097.42524433])